MaterialCollector/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaterialCollector.Controllers
{
    public class BaseController : Controller
    {        
        [NonAction]
        public ActionResult ResponseJson(string message, object data = null)
        {
            // to do : 動態產生object
            //dynamic dataOb = new ExpandoObject();
            //dataOb.msg = message;

            //if(data != null)
            //{
            //    foreach (var p in data.GetType().GetProperties())
            //        dataOb
            //}
            

            return new JsonResult
            {
                Data = new
                {
                    msg = message,
                    data = data
                }
            };
            
        }
    }
}

MaterialCollector/Controllers/CategoryController.cs
using DbService.Model;
using DbService.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaterialCollector.Controllers
{
    public class CategoryController : BaseController
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetCategory(string mainCategory)
        {
            ICategoryService categoryService = new CategoryService();

            var categorys = categoryService.GetCategoryListByMainCategory(mainCategory)
                .Select(s =>
                {
                    return new { s.Id, s.MainCategory, s.SubCategory, Num = s.MaterialCount };
                });

            return ResponseJson("", categorys);
        }

        public ActionResult GetALLMainCategory()
        {
            ICategoryService categoryService = new CategoryService();
            var mainCategorys = categoryService.GetALLMainCategory();
            return ResponseJson("", mainCategorys);
        }

        [HttpPost]
        public ActionResult AddCategory(string mainCategory, string subCategory)
        {
            ICategoryService categoryService = new CategoryService();

            var similarCategory = categoryService.GetSimilarCategory(mainCategory, subCategory);
            if (similarCategory != null)
            {
                var message = "已有相似的分類,主分類 : " + similarCategory.MainCategory + " ,次分類 : " + similarCategory.SubCategory;
                return ResponseJson(message);
            }

            Category newCategory = new Category();
            newCategory.MainCategory = mainCategory;
            newCategory.SubCategory = subCategory;

            categoryService.InsertCategory(newCategory);

            return ResponseJson("新增成功");
        }
        [HttpPost]
        public ActionResult UpdateCategory(int categoryId, string mainCategory, string subCategory)
        {
            ICategoryService categoryService = new CategoryService();

            var similarCategory = categoryService.GetSimilarCategory(mainCategory, subCategory);
            if (similarCategory != null)
            {
                var message = "已有相似的分類,主分類 : " + similarCategory.MainCategory + " ,次分類 : " + similarCategory.SubCategory;
                return ResponseJson(message);
            }

            var category = categoryService.UpadteCategory(categoryId, mainCategory, subCategory);
            return ResponseJson("修改成功", new { category.MainCategory, category.SubCategory });
        }

        [HttpPost]
        public ActionResult DeleteCategory(int categoryId)
        {
            ICategoryService categoryService = new CategoryService();

            categoryService.DeleteCategoryById(categoryId);

            return ResponseJson("刪除成功");
        }
    }
}

MaterialCollector/Controllers/HomeController.cs
using DbService.Model;
using DbService.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaterialCollector.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {            
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MaterialCollector/Controllers/MaterialController.cs
using DbService.Model;
using DbService.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaterialCollector.Controllers
{
    public class MaterialController : BaseController
    {
        // GET: Material
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMaterial(string content, string comment, int[] categoryId)
        {
            if(categoryId == null || categoryId.Length < 1)
                return ResponseJson("請選擇分類");

            IMaterialService materialService = new MaterialService();           

            materialService.InsertMaterial(content, comment, categoryId);

            return ResponseJson("新增成功");
        }

        [HttpPost]
        public ActionResult GetMaterial(int? categoryId, string[] orderbyMember, string[] orderby, int page, int count)
        {
            if (orderbyMember.Length != orderby.Length)
                return ResponseJson("資料有誤");

            try
            {
                IMaterialService materialService = new MaterialService();

                // youtube url 需改成 embed
                var materials = materialService.GetMaterials(categoryId, orderbyMember, orderby, page, count).Select(m =>
                {
                    var uri = new Uri(m.Url);
                    var vedioId = HttpUtility.ParseQueryString(uri.Query).Get("v");
                    return new
                    {
                        Id = m.Id,
                        Url = "https://www.youtube.com/embed/" + vedioId,
                        m.UsedCount,
                        m.Comment,
                        LastUsedTime = (m.LastUsedTime == DateTime.MinValue) ? string.Empty : m.LastUsedTime.ToString("yyyy/MM/dd")
                    };
                });

                return ResponseJson("", materials);
            }
            catch (Exception e)
            {
                return ResponseJson(e.Message);
            }
        }

        [HttpPost]
        public ActionResult DeleteMaterial(int materialId)
        {
            IMaterialService materialService = new MaterialService();

            materialService.DeleteMaterialById(materialId);

            return ResponseJson("刪除成功");
        }

        [HttpPost]
        public ActionResult UseMaterial(int materialId, string noteContent)
        {
            IMaterialService materialService = new MaterialService();
            var material = materialService.UseMaterial(materialId, noteContent);
            if (material == null)
                return ResponseJson("資料錯誤，找不到此素材");

            var returnInfo = new
            {
                UsedCount = material.MaterialNote.Count,
                LastUsedTime = material.MaterialNote.FirstOrDefault().CreatedOn.ToString("yyyy/MM/dd")
            };

            return ResponseJson("新增使用紀錄成功", returnInfo);
        }

        [HttpPost]
        public ActionResult GetMaterialNotes(int materialId)
        {
            IMaterialService materialService = new MaterialService();
            var material = materialService.GetMaterialById(materialId);
            if (material == null)
                return ResponseJson("資料錯誤，找不到此素材");

            var notes = material.MaterialNote.OrderByDescending(mn => mn.CreatedOn).Select(mn =>
            {
                return new { mn.Id, mn.Content, CreatedOn = mn.CreatedOn.ToString("yyyy/MM/dd hh:mm:ss") };
            }).ToList();

            return ResponseJson("", notes);
        }

        [HttpPost]
        public ActionResult DeleteMaterialNote(int materialNoteId)
        {
            IMaterialService materialService = new MaterialService();
            var material = materialService.DeleteMaterialNoteById(materialNoteId);

            var returnInfo = new
            {
                UsedCount = material.MaterialNote.Count,
                LastUsedTime = material.MaterialNote.FirstOrDefault().CreatedOn.ToString("yyyy/MM/dd")
            };

            return ResponseJson("刪除成功", returnInfo);
        }
    }
}

MaterialCollector/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="categoryControl">
    <div class="jumbotron">
        <div>分類以<span style="color:red;font-size:24px;">主要類別 + 次要類別</span>作為分類，EX :</div>
        <ul>
            <li>婚禮(主要類別) + 迎娶、宴客、致詞(次要類別)</li>
            <li>商業(主要類別) + 悲、歡、離、合(次要類別)</li>
        </ul>
    </div>
    <div class="form-inline">
        <div class="form-group">
            <label for="mainCategory">主要類別</label>
            <input type="text" class="form-control smallfs" v-model="mainCategory">
        </div>
        <div class="form-group">
            <label for="subCategory">次要類別</label>
            <input type="text" class="form-control smallfs" v-model="subCategory">
        </div>
        <button type="button" class="btn btn-default smallfs" v-on:click="AddCategory()">新增分類</button>
    </div>
    <table style="margin-top:30px;" class="table table-hover table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    <span>分類</span>
                    <select v-model="selectedMainCategory" class="form-control smallfs" style="height:36px;width:auto;display:inline-block">
                        <option class="smallfs" v-for="main in mainCategorys" v-bind:value="main">{{main}}</option>
                    </select>
                </th>
                <th>素材數量</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr is="categorytmp" v-for="category in categorys" v-bind="category"></tr>
        </tbody>
    </table>
</div>

<script type="text/x-template" id="categorytmp">
    <tr v-show="show">
        <td v-show="!isEdit">{{innerMainCategory + " - " + innderSubCategory}}</td>
        <td v-show="isEdit">
            <input class="form-control smallfs" v-model="editMainCategory" size="8" style="width:auto;display:inline-block" /> - <input class="form-control smallfs" v-model="editSubCategory" size="8" style="width:auto;display:inline-block" />
        </td>
        <td>{{Num}}</td>
        <td>
            <button v-show="!isEdit" type="button" class="btn btn-danger smallfs" v-on:click="DeleteCategory()">
                <span class="glyphicon glyphicon-remove-circle iconfs"></span>
                <span> 刪除類別</span>
            </button>
            <button v-show="!isEdit" type="button" class="btn btn-warning smallfs" v-on:click="ToggleEdit()">
                <span class="glyphicon glyphicon-remove-circle iconfs"></span>
                <span> 修改類別</span>
            </button>
            <button v-show="isEdit" type="button" class="btn btn-success smallfs" v-on:click="UpdateCategory()">
                <span class="glyphicon glyphicon-remove-circle iconfs"></span>
                <span> 確定修改</span>
            </button>
            <button v-show="isEdit" type="button" class="btn btn-default smallfs" v-on:click="ToggleEdit()">
                <span class="glyphicon glyphicon-remove-circle iconfs"></span>
                <span> 取消修改</span>
            </button>
        </td>
    </tr>
</script>

<script>
    Vue.component('categorytmp', {
        template: '#categorytmp',
        props: ['Id', 'MainCategory', 'SubCategory', 'Num'],
        data: function () {
            return {
                show: true,
                isEdit: false,
                innerMainCategory: this.MainCategory,
                innderSubCategory: this.SubCategory,
                editMainCategory: this.MainCategory,
                editSubCategory: this.SubCategory,
            }
        },
        watch: {
            'MainCategory': function (val) {
                this.innerMainCategory = val;
                this.editMainCategory = val;
            },
            'SubCategory': function (val) {
                this.innderSubCategory = val;
                this.editSubCategory = val;
            },
        },
        methods: {
            DeleteCategory: function () {
                if (!confirm("確定刪除分類嗎?"))
                    return;

                var self = this;
                axios.post('/Category/DeleteCategory', {
                    categoryId: self.Id,
                })
                    .then(function (response) {
                        console.log(response);
                        self.show = false;
                        alert(response.data.msg);
                    })
                    .catch(function (error) {
                        alert(error);
                    })
            },
            ToggleEdit: function () {
                this.isEdit = !this.isEdit;
            },
            UpdateCategory: function () {
                var self = this;
                axios.post('/Category/UpdateCategory', {
                    categoryId: self.Id,
                    mainCategory: self.editMainCategory,
                    subCategory: self.editSubCategory,
                })
                    .then(function (response) {
                        console.log(response);
                        if (response.data.data) {
                            self.innerMainCategory = response.data.data.MainCategory;
                            self.editMainCategory = response.data.data.MainCategory;
                            self.innderSubCategory = response.data.data.SubCategory;
                            self.editSubCategory = response.data.data.SubCategory;
                            self.ToggleEdit();
                        }
                        alert(response.data.msg);
                    })
                    .catch(function (error) {
                        alert(error);
                    })
            },
        }
    });

    var categoryControl = new Vue({
        el: '#categoryControl',
        data: {
            categorys: [],
            mainCategorys: ['全部'], // 所有主類別
            mainCategory: '',
            subCategory: '',
            selectedMainCategory:'全部',
        },
        methods: {
            GetCategory: function () {
                var self = this;
                var main = (self.selectedMainCategory === "全部") ? "" : self.selectedMainCategory;
                axios.post('/Category/GetCategory', {
                    mainCategory: main,
                })
                    .then(function (response) {
                        console.log(response);
                        self.categorys = response.data.data;
                    })
                    .catch(function (error) {
                        console.log(error);
                    })
            },
            GetALLMainCategory: function () {
                var self = this;
                axios.post('/Category/GetALLMainCategory')
                    .then(function (response) {
                        console.log(response.data.data);
                        self.mainCategorys = _.concat(self.mainCategorys, response.data.data);
                    })
                    .catch(function (error) {
                        console.log(error);
                    })
            },
            AddCategory: function () {
                var self = this;
                axios.post('/Category/AddCategory', {
                    mainCategory: self.mainCategory,
                    subCategory: self.subCategory
                })
                    .then(function (response) {
                        console.log(response);
                        self.GetCategory();
                        alert(response.data.msg);
                    })
                    .catch(function (error) {
                        alert(error);
                    })
            },
        },
        watch: {
            selectedMainCategory: function (val) {
                this.GetCategory();
            },
        },
        created: function () {
            console.log(this + ' created');
            this.GetCategory();
            this.GetALLMainCategory();
        },
        mounted: function () {
            console.log(this + ' mounted');
        }
    });
</script>

MaterialCollector/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<p style="margin-top:30px;">這是一個關於笨笨女孩與聰明男孩的故事,男孩為了方便女孩管理影片剪輯素材,於是誕生了這個管理平台...</p>

MaterialCollector/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MaterialCollector/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>最新素材</h1>    
</div>

MaterialCollector/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
    <script src="~/Scripts/Vue/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>    
    <script src="~/Scripts/lodash.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">    
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("設定", "Index", "Category")</li>
                    <li>@Html.ActionLink("素材", "Index", "Material")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>                                        
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>有問題請來信</p>
        </footer>
    </div>

   
    @RenderSection("scripts", required: false)
</body>
</html>